### PR TITLE
Fix decay issues with PointClouds and LaserScans

### LINKED ISSUE #4892: Data are accumulated on the source frame instead of the display frame when decay time > 0
**Description**
In the 3D panel, the accumulation of laser scan (not sure about other types) seems to be problematic when setting a positive value of decay time. I expect its points to be accumulated on the display frame, like in RViz. But it seems to be accumulating on the data source frame or other way. 

- Version: 1.32.0-dev
- OS: Windows 11
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
- ROS distro (if applicable):

**Steps To Reproduce**

Open a bag that has a laser scan topic, where the scan data are associated on a sensor frame (e.g. "laser"), and the sensor frame is moving w.r.t. a world frame (e.g. "world"), with correct transformations on /tf.
Open a 3D panel, in its settings, set the Display frame to be the world frame and the Follow mode to be Fixed. Then turn on the scan topic, and set its decay time to a positive number such as 100.

**Expected Behavior**
The scan points are accumulated on the world frame, so that they form the shape of the environment when the robot is moving.

**Actual Behavior**
The accumulated points move with the robot.

See an example below: 
(on the right hand side there is the accumulation of the same data in RViz, for comparison)

foxglove3

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Fixed issues with PointCloud and LaserScan messages displaying incorrectly in the 3D panel when their `pose` changed, or when the Decay Time setting was used.

**Description**
Fixes #4892
Fixes FG-967

Issues fixed:
- The `pose` of the latest history item was not being updated after it was initially created.
- LaserScans needs `itemSize=1` for the `position` attribute, but it was sometimes using the shared `createGeometry` function which uses `itemSize=3`

Test data: [gh4892_decay_time.mcap.zip](https://github.com/foxglove/studio/files/10240214/gh4892_decay_time.mcap.zip)
Test data with VelodyneScans: Udacity-CHX_001-cal_loop.bag

<details>
<summary>Test script:</summary>

```python
import math
import struct
from os import path
from tqdm import tqdm
from mcap_protobuf.writer import Writer
from foxglove_schemas_protobuf.LaserScan_pb2 import LaserScan
from foxglove_schemas_protobuf.PointCloud_pb2 import PointCloud
from foxglove_schemas_protobuf.FrameTransform_pb2 import FrameTransform
from foxglove_schemas_protobuf.PackedElementField_pb2 import PackedElementField
from pyquaternion import Quaternion


with open(path.splitext(path.basename(__file__))[0] + ".mcap", "wb") as stream:
    writer = Writer(stream)

    duration_ns = 10_000_000_000
    nframes = 100
    for frame in tqdm(range(0, nframes)):
        t = int(frame * duration_ns / nframes)

        if frame%10==0:
            q = Quaternion(axis=[0, 0, 1], angle=math.pi/4 * frame/nframes)
            scan = LaserScan()
            scan.frame_id = "sensor1"
            scan.timestamp.FromNanoseconds(t)
            scan.start_angle = 0
            scan.end_angle = 0.2
            scan.pose.position.x = 1 * frame/nframes
            scan.pose.orientation.x = q.x
            scan.pose.orientation.y = q.y
            scan.pose.orientation.z = q.z
            scan.pose.orientation.w = q.w
            scan.ranges[:] = [1, 1, 1, 1, 1, 1, 1]
            scan.intensities[:] = [1, 2, 3, 4, 5, 6, 7]
            writer.write_message("scan", scan, t)

            cloud = PointCloud()
            cloud.frame_id = "sensor2"
            cloud.timestamp.FromNanoseconds(t)
            cloud.fields.add(
                name = "x",
                offset = 0,
                type = PackedElementField.FLOAT32
            )
            cloud.fields.add(
                name = "y",
                offset = 4,
                type = PackedElementField.FLOAT32
            )
            cloud.fields.add(
                name = "z",
                offset = 8,
                type = PackedElementField.FLOAT32
            )
            cloud.fields.add(
                name = "i",
                offset = 12,
                type = PackedElementField.UINT8
            )
            data = bytearray(13 * 7)
            cloud.point_stride = 13
            for i in range(0, 7):
                struct.pack_into("<fffB", data, i * 13, 1, 0.3*i/7, 0, i)
            cloud.pose.position.x = 1 * frame/nframes
            q = Quaternion(axis=[0, 0, 1], angle=-math.pi/4 * frame/nframes)
            cloud.pose.orientation.x = q.x
            cloud.pose.orientation.y = q.y
            cloud.pose.orientation.z = q.z
            cloud.pose.orientation.w = q.w
            cloud.data = bytes(data)
            writer.write_message("cloud", cloud, t)

        tf = FrameTransform()
        tf.parent_frame_id = "base"
        tf.child_frame_id = "sensor1"
        tf.timestamp.FromNanoseconds(t)
        tf.translation.y = 3 * frame/nframes
        tf.rotation.w = 1
        writer.write_message("tf", tf, t)

        tf = FrameTransform()
        tf.parent_frame_id = "base"
        tf.child_frame_id = "sensor2"
        tf.timestamp.FromNanoseconds(t)
        tf.translation.y = -3 * frame/nframes
        tf.rotation.w = 1
        writer.write_message("tf", tf, t)

        tf = FrameTransform()
        tf.parent_frame_id = "world"
        tf.child_frame_id = "base"
        tf.timestamp.FromNanoseconds(t)
        tf.translation.x = frame/nframes
        tf.rotation.w = 1
        writer.write_message("tf", tf, t)

    writer.finish()
    stream.close()
```

</details>

### CODE REVIEW

File: packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts [hunk 1]
```diff
@@ -198,6 +198,7 @@ export class PointCloudRenderable extends PointsHistoryRenderable<PointCloudUser
 
     latestEntry.receiveTime = receiveTime;
     latestEntry.messageTime = messageTime;
+    latestEntry.points.userData.pose = getPose(pointCloud);
```
Comment (jhurliman) [inline packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts:201]: This is the heart of the fix?

**Review by jhurliman — APPROVED** [review]

**Review by snosenzo — APPROVED** [review]

File: packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts (hunk 1 above)
Comment (jtbandes) [reply packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts:201]: One of them. There is another of these in LaserScans.ts, and there's also `createLaserScanGeometry` which now correctly uses itemSize=1
