### PR TITLE
Fix File > Open menu items not working

### LINKED ISSUE #6736: File open options do nothing
**Description**

File > `Open...`
File > `Open local file...`
File > `Open connection...`

No longer work. Only able to get the open dialog by opening a new window.

- Version: 1.68.0
- Platform: macos 13.3.1 (a)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

Open studio, load a local file or connection. Click File > Open. Nothing occurs.

**Expected Behavior**

A dialog box opens to allow the user to open a file or connection.

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Fixed an issue where some File menu options didn't work on macOS.

**Description**
Related to changes made in https://github.com/foxglove/studio/pull/6273, https://github.com/foxglove/studio/pull/6698 & https://github.com/foxglove/studio/pull/6699
Fixes #6736 

Clicking "Open", "Open local file", or "Open connection" in the system menu didn't work, instead logging this error:

```
(node:31329) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'webContents')
    at simulateUserClick (webpack-internal:///../../../studio/packages/studio-desktop/src/main/simulateUserClick.ts:13:9)
    at click (webpack-internal:///../../../studio/packages/studio-desktop/src/main/StudioWindow.ts:427:92)
    at MenuItem.click (node:electron/js2c/browser_init:2:30795)
    at a._executeCommand (node:electron/js2c/browser_init:2:36191)
```

The root cause here was that `#rebuildFileMenu()` accesses `this.#browserWindow`, but it was invoked in the constructor before `this.#browserWindow` was set. 

This is possible due to a soundness hole in TypeScript — the following code compiles cleanly but produces an error at runtime:
https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC0G8BQ1oGIIBcBOAuaW2AlgHYDmA3EitMAPYmECuwmd2AFAJSI2qYALIhAB0aAGZ063Kqn5DRGHNAC80AERD1s6AF9qqCVO685tBhDogApiJB0yHdQBlr5QdGG51AGmiDhMUI7NzJBLh19fSQSawB3OBkgA

Certain other languages avoid this problem by requiring properties to be initialized before methods can be called on `this`: https://swiftfiddle.com/?c=H4sIAAAAAAAAAzWOvQrDMAyEX%2BXQZEMxdCgUQ6eu3bpqMSY%2FhiIXW8kS8u5xcAs3iLtPx20UyVP8hFrxxMYCrKGgavF4a0kysZxmkqTGdgAYcza2n43EA0xzYjqdvfPfktagA8ZFYsf%2Fvy0RNUyvQSadkaoHs2k1LuZF1DLZX08TXWht%2B27u7q60HzyPDdGtAAAA

This PR also introduces some changes to allow `using` declarations in test code (more tsconfig changes may be required later to introduce it in app code).

### CODE REVIEW

File: packages/studio-desktop/src/main/index.ts [hunk 1]
```diff
@@ -292,6 +298,7 @@ export async function main(): Promise<void> {
     });
 
     initialWindow.load();
+    Menu.setApplicationMenu(initialWindow.getMenu()); // When the app is launching for the first time we don't receive the browser-window-focus event.
```
Comment (snosenzo) [inline packages/studio-desktop/src/main/index.ts:301]: This is actually what fixes the bug right?
I also don't see how the code is related to the comment

**Review by snosenzo — APPROVED** [review]
looks good to me, couple minor questions

File: packages/studio-desktop/src/main/index.ts (hunk 1 above)
Comment (jtbandes) [reply packages/studio-desktop/src/main/index.ts:301]: This fixes another bug I noticed along the way. The main bug is fixed by the changes to the StudioWindow class
