### PR TITLE
Fix PanelList keyboard interactions

### LINKED ISSUE #4500: Change panel dropdown doesn't let me type some characters
image

I can't type `c`, `s`, `f`, or `r` as the first character in the search box, because it highlights menu entries in the top level menu.

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
Fixes an issue with type to search in the PanelList component

**Description**
Prevents keyboard events from propagating out of the PanelList text field and triggering menu events in the parent menu.

Also fixes a React forwardRef error.

Fixes #4500

### CODE REVIEW

File: packages/studio-base/src/components/PanelList/index.tsx [hunk 1]
```diff
@@ -395,6 +395,11 @@ function PanelList(props: Props): JSX.Element {
 
   const onKeyDown = React.useCallback(
     (e: React.KeyboardEvent) => {
+      // Prevent key down events from triggering the parent menu, if any.
+      if (e.key !== "Escape") {
```
Comment (snosenzo) [inline packages/studio-base/src/components/PanelList/index.tsx:399]: does this interrupt browser shortcuts with ctrl and shift?

Comment (snosenzo) [reply packages/studio-base/src/components/PanelList/index.tsx:399]: ah wait I tested, no it doesn't 👍

**Review by snosenzo — APPROVED** [review]

**Review by jtbandes — APPROVED** [review]

File: packages/studio-base/src/components/PanelList/index.tsx (hunk 1 above)
Comment (foxymiles) [reply packages/studio-base/src/components/PanelList/index.tsx:399]: Good thinking to test that.
