### PR TITLE
Incorrect use of "Render Frame" for grid "Frame" selection.

### LINKED ISSUE #4619: Incorrect use of "Render Frame" for grid "Frame" selection.
image

When selecting the grid frame, the dropdown lists a `<Render Frame>` option. We have no such concept elsewhere in the 3D panel settings. This option refers to the grid rendering in the `Display frame`. This option text should match the setting label.

### PR DESCRIPTION
**Pull request by snosenzo**
**User-Facing Changes**
 n/a

**Description**
 - changed `Render Frame` to `Display frame`
 - also updated a log that was using similar terminology

Fixes #4619

### CODE REVIEW

**Review by defunctzombie — APPROVED** [review]
👍  do we wan to use the `< >` as before or have without?

File: packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts [hunk 1]
```diff
@@ -1255,7 +1255,7 @@ export class Renderer extends EventEmitter<RendererEvents> {
         this.fixedFrameId = undefined;
         return;
       } else {
-        log.debug(`Setting render frame to ${this.renderFrameId}`);
+        log.debug(`Setting display frame to ${this.renderFrameId}`);
```
Comment (jtbandes) [inline packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts:1258]: I'd omit this change, it's making the debug log message inconsistent with the code. The variable is named `renderFrameId`
