### PR TITLE
Fix `nav_msgs/OccupancyGrid` value showing up as transparent

### LINKED ISSUE #5320: nav_msgs/OccupancyGrid not displaying correctly
**Description**
The value of 100 in message OccupancyGrid will be displayed in very light grey color while in rviz its black.

- Version: 1.39.1
- Platform: macos

**Steps To Reproduce**

**Expected Behavior**
100 should be displayed as black in nav_msgs/OccupancyGrid.

Screenshot 2023-02-10 at 16 59 45
Screenshot 2023-02-10 at 17 00 13

### PR DESCRIPTION
**Pull request by snosenzo**
**User-Facing Changes**

 - Fix `nav_msgs/OccupancyGrid` value === 100 showing up as transparent instead of black

**Description**
- occupancy grid show value === 100 as black instead of transparent
- add story to for occupancy grids

FG-1862
Fixes #5320

### CODE REVIEW

File: packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts [hunk 1]
```diff
@@ -349,7 +349,7 @@ function updateTexture(
           rgba[offset + 0] = 0;
           rgba[offset + 1] = 0;
           rgba[offset + 2] = 0;
-          rgba[offset + 3] = 0;
+          rgba[offset + 3] = 255;
```
Comment (jtbandes) [inline packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts:352]: Do we still need this if condition for `t===1`?

Comment (snosenzo) [reply packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts]: good catch, doesn't look like it

**Review by jtbandes — APPROVED** [review]
