### PR TITLE
Fix Windows deep link handling by encoding with base64

### LINKED ISSUE #4896: Opening Timeline Recording to Desktop on Windows Fails
**Description**
Opening a recording from timeline to desktop on Windows results in a blank studio client.

- Version: 1.33.0
- OS: Windows

**Steps To Reproduce**
1. Set Studio to open links in desktop 
image
2. Select recording time-range in Console
3. Attempt to open time-range

**Expected Behavior**
Recording range opened in studio

**Actual Behavior**
Blank window

cc: @amacneil @rrryanc

### PR DESCRIPTION
**Pull request by jtbandes**
**User-Facing Changes**
Fixed an issue on Windows where `foxglove://` links would open a blank Foxglove Studio window.

**Description**
Fixes #4896 

It seems like passing arbitrary arguments to the renderer is not safe on windows for some reason. We work around the problem by base64-encoding.

See: https://github.com/electron/electron/issues/31168, https://github.com/electron/electron/issues/32064

### CODE REVIEW

File: desktop/preload/index.ts [hunk 1]
```diff
@@ -104,7 +104,11 @@ const desktopBridge: Desktop = {
     await ipcRenderer.invoke("updateNativeColorScheme");
   },
   getDeepLinks(): string[] {
-    return window.process.argv.filter((arg) => arg.startsWith("foxglove://"));
+    const deepLinksArg = window.process.argv
```
Comment (defunctzombie) [inline desktop/preload/index.ts:107]: Please extract this logic to a function. I'm thinking one you can pass an argument array to that finds the argument you want and then returns the deserialized deep links. Add a unit test for it. 🙏

**Comment by defunctzombie** [comment]
Good stuff
