### PR TITLE
Use local paths state in plot legend to improve interactivity

### LINKED ISSUE #3146: Keyboard input sporadically disappears
**Description**
I've experienced this problem several times now (and my coworker has as well) where the characters we type in a plotting legend show up briefly, but then disappear, and then sometimes come back and sometimes not. It also is usually not all the characters I type - they are sporadic.

- Version: 1.5.1
- OS: Ubuntu 20.04

**Steps To Reproduce**

1. Open a live connection (I used turtlesim running on the same machine as foxglove in this example).
2. Create a plot panel subscribe to several topics (it seems that this bug is easier to reproduce when Foxglove is given a lot to do)
3. Type out some topic names

**Expected Behavior**
Typed words should appear on the screen as typed

**Actual Behavior**
Typed words get jumbled, with characters randomly dropped, or dropped and then re-added later in the string.

For example, I might try to type "hello/test/123/abc". Right after I type the "ab", they go away, so I'm left with "hello/test/123/c".

Or, the missing characters might come back. For example, if I type "this/is/a/test", the "th" in "this" disappears and doesn't come back, but also, "test" disappears, and _does_ come back after a second, leaving us with "is/is/a/test".

I captured a video of those two examples here, although its harder to understand if you don't see where my hands are typing.

https://user-images.githubusercontent.com/43035541/161804578-f8bd82a7-7024-46a0-a09e-2f15352a0ae6.mp4

Sometimes the characters come back later in the string, which is the worst of all. For example, "test/123/abc" might come back as "test/1/ab23c". I wasn't able to get an example of that on camera though.

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
This improves interactivity of the plot legend message path input.

**Description**
Currently we immediately flush every edit to a plot message path input to  the panel config, and this results in studio doing a lot of work including updating subscriptions, rebuilding callbacks etc and re-rendering the entire plot on every keystroke.

The approach here is for the plot legend to maintain its own local copy of the paths and use a debounced flush to push this back to the underlying panel config.

It also adds a few missing memoizations.

Fixes #3146

### CODE REVIEW

File: packages/studio-base/src/panels/Plot/PlotLegend.tsx [hunk 1]
```diff
@@ -228,26 +230,42 @@ const useStyles = makeStyles((theme: Theme) => ({
...
+  const [localConfig, setlocalConfig] = useState({ paths: props.paths });
+
+  const debouncedSaveConfig = useDebouncedCallback((newConfig: Partial<PanelConfig>) => {
+    props.saveConfig(newConfig);
+  }, 500);
+
+  const saveConfig = useCallback(
+    (newConfig: Partial<PlotConfig>) => {
+      setlocalConfig((prevConfig) => ({ ...prevConfig, ...newConfig }));
+      debouncedSaveConfig(newConfig);
```
Comment (defunctzombie) [inline packages/studio-base/src/panels/Plot/PlotLegend.tsx:262]: Technically we are saving a different thing than what we are setting localConfig to here since `newConfig` might not equal `{ ...prevConfig, ...newConfig}`.

Maybe the call to debouncedSaveConfig should happen in a useEffect that depends on `localConfig` ?

**Review by defunctzombie — APPROVED** [review]

File: packages/studio-base/src/panels/Plot/PlotLegend.tsx (hunk 1 above)
Comment (foxymiles) [reply packages/studio-base/src/panels/Plot/PlotLegend.tsx:262]: I think we're ok in that case because the semantics of `saveConfig` are to merge not replace.

But the other issue with this approach is that all updates to config are debounced. I think I'll rework this to just wrap and debounce the `paths` element of config because that's the only part that is affected by this issue.
