### PR TITLE
Fix gaps in data platform plots

### LINKED ISSUE #2956: Plots from data platform span gaps
**Description**
When plotting data from data platform plots are incorrectly connecting points across gaps in data.

- Version: 1.2.0
- OS: macOS

**Steps To Reproduce**

1. Open a file longer than 20 seconds from data platform into studio.
2. Plot some value.
3. Click at different points in the playback bar to load different data segments

**Expected Behavior**
Gaps in fetched data should not be connected.

**Actual Behavior**
Gaps are connected by lines. See screenshot.

Screen Shot 2022-03-01 at 1 33 28 PM

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
This fixes an issue with plotting incompletely fetched data platform data.

**Description**
Currently when we plot data fetched from data platform we incorrectly connect discontiguous segments. This adds logic to insert empty blocks where we have gaps in our fetched data.

Fixes #2956 

Screenshot of plot with gaps in data after this patch:
Screen Shot 2022-03-02 at 9 47 24 AM

### CODE REVIEW

File: packages/studio-base/src/players/FoxgloveDataPlatformPlayer/MessageMemoryCache.ts [hunk 1]
```diff
@@ -278,4 +278,21 @@ export default class MessageMemoryCache {
...
+  // Rebuilds block cache, interspersing empty blocks where there are time gaps
+  // in our loaded ranges.
+  private _rebuildBlockCache() {
+    const newBlocks: MemoryCacheBlock[] = [];
+    for (let i = 0; i < this.loadedRanges.length; i++) {
+      if (
+        i > 0 &&
+        isLessThan(this.loadedRanges[i - 1]!.range.end, this.loadedRanges[i]!.range.start)
+      ) {
+        newBlocks.push({ messagesByTopic: {}, sizeInBytes: 0 });
```
Comment (jtbandes) [inline packages/studio-base/src/players/FoxgloveDataPlatformPlayer/MessageMemoryCache.ts:291]: Why not just newBlocks.push(undefined)?

**Review by jtbandes — APPROVED** [review]

File: packages/studio-base/src/players/FoxgloveDataPlatformPlayer/MessageMemoryCache.ts (hunk 1 above)
Comment (foxymiles) [reply packages/studio-base/src/players/FoxgloveDataPlatformPlayer/MessageMemoryCache.ts:291]: It was just easier with the existing non-optional typedefs.

Comment (foxymiles) [reply packages/studio-base/src/players/FoxgloveDataPlatformPlayer/MessageMemoryCache.ts:291]: I've changed it to undefined. Thanks for the suggestion.
