### PR TITLE
Safely parse color values in the ColorSwatch component

### LINKED ISSUE #4497: App crashes when pasting color value into Gradient picker
The app crashes when pasting a color value into the Gradient picker (settings editor)

1. Open the `Colors` storybook: https://603ec8bf7908b500231841e2-ftdjtiqpey.chromatic.com/?path=/story/components-settingstreeeditor--colors
2. Click on the first gradient color box
3. Copy the hex color value
4. Click on the second gradient color box
5. Paste the color value

https://user-images.githubusercontent.com/84792/192801718-1cdb6294-c1ee-4788-81b6-e917a8c56dde.mov

```
Minified MUI error #9; visit https://mui.com/production-error/?code=9&args[]=000000ff for the full message.
```

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
None

**Description**
Use tinycolor to parse the incoming color value before passing it on to MUI's color utility to avoid throwing an exception on an invalid color.

Fixes #4497

### CODE REVIEW

File: packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx [hunk 1]
```diff
@@ -2,7 +2,13 @@
 // License, v2.0. If a copy of the MPL was not distributed with this
 // file, You can obtain one at http://mozilla.org/MPL/2.0/
 
-import { styled as muiStyled } from "@mui/material";
+import { styled as muiStyled, Theme } from "@mui/material";
+import tinycolor from "tinycolor2";
+
+function calculateBorderColor(theme: Theme, color: string): string {
+  const parsedColor = tinycolor(color);
+  return parsedColor.isValid() ? theme.palette.getContrastText(parsedColor.toHexString()) : color;
```
Comment (jhurliman) [inline packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx:10]: Should this return undefined if the color is invalid?

Comment (foxymiles) [reply packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx:10]: Do we want the resulting CSS to be `border: 1px solid undefined`?

Comment (foxymiles) [reply packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx:10]: I guess we could just return white or black or gray if the color is invalid.

Comment (2metres) [reply packages/studio-base/src/components/SettingsTreeEditor/inputs/ColorSwatch.tsx:10]: Maybe `#00000000` ?
