### PR TITLE
Avoid unnecessary readvertisments of foxglove websocket client channels

### LINKED ISSUE #6051: Making layout changes causes unadvertisement / advertisement of published topics
I added the `clientPublish` capability to my foxglove server (which is a great feature by the way 😄 )

I have two different publish panels on my layout. Now, when I make *some* kind of UI changes (e.g. add a new panel, delete a panel), the published channels are first unadvertised and then advertised again.
Shouldn't they be persistent? The same way that subscriptions are not changed when changes are made to unrelated tabs?

To reproduce:
Have a websocket server with the publish capability. Add a publisher panel. Then add a new publisher panel. The first panel gets unadvertised, and then both panels get advertised again.

Sometime (but not all the time) this is also the case when deleting an unrelated panel (e.g. Image panel).

### PR DESCRIPTION
**Pull request by achim-k**
**User-Facing Changes**
- Avoid unnecessary readvertisments of foxglove websocket client channels

**Description**
This PR makes several changes to avoid unnecessary advertisements / readvertisements of client channels when using the foxglove websocket connection:

- The player's `setPublishers` method is only called when topic or schemaName are valid (not empty)
- The player's datatypes are only updated if they actually changed
  - This is particular relevant when connecting to a foxglove_bridge instance, as client channels get also advertised as server channels.
- In the player's `setPublishers` method, we now determine which publications have been added / removed and only react on these changes rather than resetting all client publications.

Fixes #6051

### CODE REVIEW

File: packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts [hunk 1]
```diff
@@ -618,10 +618,18 @@ export default class FoxgloveWebSocketPlayer implements Player {
           : new JsonMessageWriter();
 
         // Add type definitions for service response and request
+        let datatypesNeedsUpdate = false;
         for (const [name, types] of [...parsedRequest.datatypes, ...parsedResponse.datatypes]) {
+          if (this.#datatypes.has(name)) {
+            // Assumption: Schemas do not change.
+            continue;
```
Comment (jtbandes) [inline packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts:625]: Do we need to make this assumption? Can we verify the assumption and raise an error to the user if it doesn't hold instead of silently failing?

File: packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts [hunk 2]
```diff
@@ -618,10 +618,18 @@ export default class FoxgloveWebSocketPlayer implements Player {
...
+          }
+          datatypesNeedsUpdate = true;
           this.#datatypes.set(name, types);
         }
-        this.#datatypes = new Map(this.#datatypes); // Signal that datatypes changed.
+        if (datatypesNeedsUpdate) {
+          this.#datatypes = new Map(this.#datatypes); // Signal that datatypes changed.
```
Comment (jtbandes) [inline packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts:631]: This pattern of mutating the existing map and then cloning later seems weird to me. Feels like we should clone as soon as we know we need to produce a new map, then add items to the new map.

File: packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts [hunk 3]
```diff
@@ -854,14 +873,45 @@ export default class FoxgloveWebSocketPlayer implements Player {
...
+    }
+
+    // Determine new & removed publications.
+    const currentPublications = Array.from(this.#publicationsByTopic.values());
+    const removedPublications = currentPublications.filter((channel) => {
+      return (
+        uniquePublications.find(
+          ({ topic, schemaName }) => channel.topic === topic && channel.schemaName === schemaName,
+        ) == undefined
+      );
```
Comment (jtbandes) [inline packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts:892]: Why do we use `isEqual` above but a different custom comparison here?

Comment (achim-k) [reply packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts:892]: We compare different types here: `AdvertiseOptions` and [Publication](https://github.com/foxglove/studio/blob/105f2404cfe9e2dd271af38b7e62d3e2883dd29e/packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts#L70). Should I could change `Publication` to contain the entire `AdvertiseOptions`?

Comment (jtbandes) [reply packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts:870]: No worries, I didn't realize it was a different type

**Review by jtbandes — APPROVED** [review]
