### PR TITLE
Fix: use Tooltip component for Playback Control buttons

### LINKED ISSUE #1770: Seek button tooltips get stuck easily
Tooltips on the seek button often get stuck when moving the mouse randomly or clicking on the buttons.

https://user-images.githubusercontent.com/14237/132081464-364ce0a0-b4a1-46f6-ad3b-52bb94ba7bd0.mov

- Version: main @ 170e38ab
- OS: macOS

### PR DESCRIPTION
**Pull request by defunctzombie**
**User-Facing Changes**
Tooltips for playback controls no longer get stuck when you leave the button with your cursor.

**Description**
Fixes an issue with the tooltip getting stuck open on the playback
controls. This was due to mouse events not firing for disabled buttons.

This change sets the allowDisabledFocus flag for the HoverableIconButton and
uses forwardRef to allow the HoverableIconButton to exist in a <Tooltip> component parent.

Additionally, this change wraps each <Tooltip> in PlaybackControls within a <StackItem>. Since the
<Tooltip> adds a <span> component for the "layer", the gap setting on our <Stack> would result in
the buttons shifting around when the tooltip was active.

Fixes #1770

### CODE REVIEW

**Comment by defunctzombie** [comment]
@jtbandes I attempted to fix #1770 but this doesn't seem to fix the issue reliably either. Not sure if this is now a bug in fluent or in some other mouse event intercept we are doing elsewhere in the app. Prior to this fix I was able to get the tooltip stuck in the PlaybackControls story. With these changes I was not able to do that but am still able to get it stuck in the app.

File: packages/studio-base/src/components/Tooltip.tsx [hunk 1]
```diff
@@ -146,16 +147,66 @@ export function useTooltip({
...
+  }[placement];
+
   return (
-    // When studio-base is packaged for npm, we saw strange issues where React would warn about
-    // missing keys on these children, so we add explicit keys.
-    <>
-      <Fragment key="host">{host}</Fragment>
-      <Fragment key="tooltip">{tooltip}</Fragment>
-    </>
+    <TooltipHost
```
Comment (jtbandes) [inline packages/studio-base/src/components/Tooltip.tsx:196]: A problem I found with using TooltipHost was that it inserted an extra element in the dom tree, so it would mess up various CSS/layout attributes set on the wrapped component. Hence the comment on L35-36.

Comment (defunctzombie) [reply packages/studio-base/src/components/Tooltip.tsx:196]: I wonder if that accounts for the story diff with the checkboxes.

Interestingly, when I used the non-TooltipHost version of <Tooltip> around the PlaybackControls HoverButtons that produced undesirable shift in the button on hover. This was not true of the TooltipHost version.

Comment (defunctzombie) [reply packages/studio-base/src/components/Tooltip.tsx:196]: Probably keeping the cloneElement approach is better - I just wanted to rule out that itself being the issue.

**Comment by defunctzombie** [comment]
@jtbandes I found the root issue (events disabled on disabled buttons - there are some posts online about this). I've updated the PR description to highlight the changes made and why.
