### PR TITLE
Fix extension panel toolbar & content layout

### LINKED ISSUE #3386: Map Panel toolbar disappears when interacting with the map
**Description**
Map Panel toolbar disappears when interacting with the map

**Steps To Reproduce**
Open Map Panel with gps point and click map the map expands and covers Panel toolbar

### LINKED ISSUE #3389: Panel toolbar is not visible on Experimental 3D panel
**Description**
It appears that the canvas is pushing the toolbar outside of the panel frame.

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
None

**Description**
This fixes an issue with the layout of the fixed panel toolbar and panel content for extension panels. The fix is to use `display: flex` for the content wrapper to allow the content to resize logically.

Screen Shot 2022-05-18 at 11 09 00 AM

Fixes #3389 
Fixes #3386

### CODE REVIEW

File: packages/studio-base/src/components/PanelExtensionAdapter.tsx [hunk 1]
```diff
@@ -557,9 +557,20 @@ function PanelExtensionAdapter(props: PanelExtensionAdapterProps): JSX.Element {
...
+        overflow: "hidden",
+        width: "100%",
+        zIndex: 0,
+        ...style,
+      }}
+    >
       <PanelToolbar helpContent={props.help} />
-      <div style={{ width: "100%", height: "100%", overflow: "hidden" }} ref={panelContainerRef} />
+      <div style={{ flex: 1, overflow: "hidden" }} ref={panelContainerRef} />
     </div>
```
Comment (2metres) [inline packages/studio-base/src/components/PanelExtensionAdapter.tsx:574]: Using the `Stack` component could reduce the number of inline styles here

```jsx
    <Stack
      fullHeight
      fullWidth
      alignItems="stretch"
      overflow="hidden"
      style={{ zIndex: 0, ...style }}
    >
```

**Review by 2metres — APPROVED** [review]
