### PR TITLE
[New3D] PointCloud and LaserScan decay

### LINKED ISSUE #3283: Adding decay time makes point cloud disappear
**Description**
I have a file with sensible receive times in a PointCloud2 message, and incorrect "header stamp" values.

Playing back this file works fine. However, if I add "decay" to the topic in 3d panel, the 3d panel goes blank.

image

Apparently this is due to the invalid header stamp times. If we are playing back by receive time, then we should decay by receive time, and header stamp time shouldn't factor in to it.

- Version: main
- OS: web

### PR DESCRIPTION
**Pull request by jhurliman**
**User-Facing Changes**

- Implements the decay setting for PointCloud and LaserScan topics in `3D (Beta)` panel

**Description**

Fixes #3283. Implements decay for point clouds and laser scans. The original messages are not kept around (a consideration for per-point picking when that is implemented), only the GPU buffers.

Other fixes:

- Option to override setUsage() for DynamicBufferGeometry
- Don't expire transforms after 60s
- Dispose renderables in removeAllRenderables()
- Fix transform lookup when all TFs are after the search time but within maxDelta

Screen Shot 2022-06-29 at 1 50 04 PM

### CODE REVIEW

File: packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts [hunk 1]
```diff
@@ -272,58 +345,131 @@ export class PointCloudsAndLaserScans extends SceneExtension<PointCloudAndLaserS
     );
   };
 
+  // eslint-disable-next-line @foxglove/no-boolean-parameters
+  _createGeometry(topic: string, dynamic: boolean): DynamicFloatBufferGeometry {
```
Comment (jtbandes) [inline packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts:349]: Remove lint suppression and pass in Usage enum directly for clarity

**Review by jtbandes — APPROVED** [review]
Do you think there's a way we can reduce the number of different places in this code where we have to initialize objects? It just gets confusing to read when there are 4 or so calls to createPoints() and other initializations. When I was adding LaserScans I might have made it worse 😬

**Comment by jhurliman** [comment]
@jtbandes I think it could be refactored to remove the create calls when initializing renderables and in the _update*() methods, check if `pointsHistory.length === 0`. That would get it down to two places, one for point clouds and one for laser scans.
