### PR TITLE
Fix copying of text from the TextMiddleTruncate component

### LINKED ISSUE #6403: Log names have a newline character in them
**Description**

Highlighting/copying the log name text always results in a newline character in the middle of the name, even though the logname is a filename with no newline character in it.

This behavior existed in previous versions of studio as well, for the log name in the left hand side panel. The log name in the titlebar on the latest foxglove has the same issue.

Screenshot 2023-07-07 at 11 19 26 AM

- Version: 1.58.0
- Platform: osx
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):

**Steps To Reproduce**

Load an mcap file, select name in title, copy, paste

**Expected Behavior** 
name should paste exactly as the filename that was loaded

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
Fix copying of text from the TextMiddleTruncate component, used in the datasource name in the app bar.

**Description**
Overrides the `onCopy` handler of the wrapper div to copy the entire text content to the clipboard.

Fixes #6403

### CODE REVIEW

File: packages/studio-base/src/components/TextMiddleTruncate.tsx [hunk 1]
```diff
@@ -79,6 +91,7 @@ export default function TextMiddleTruncate({
       className={cx(className, classes.root)}
       title={text}
       style={style}
+      onCopy={onCopy}
```
Comment (2metres) [inline packages/studio-base/src/components/TextMiddleTruncate.tsx:94]: TIL about onCopy!

**Comment by jtbandes** [comment]
This is kind of weird because you can now manually select one word or character from the text, but when you copy it you still get the full text. I'm not sure if that is better or worse than getting an unexpected newline – both seem like the app did not do what the user asked.

**Comment by foxymiles** [comment]
> This is kind of weird because you can now manually select one word or character from the text, but when you copy it you still get the full text. I'm not sure if that is better or worse than getting an unexpected newline – both seem like the app did not do what the user asked.

I don't think there's any circumstance in which a user would want a newline. This fixes the original ask from the user. Selecting the text and copying it now provides the full text of the datasource.

**Comment by foxymiles** [comment]
> Can we force selections on children to push to the parent so that we can avoid this:

IMO if this is an important workflow we want to support we should add an explicit copy button or roll it into the share dialog.

File: packages/studio-base/src/components/TextMiddleTruncate.tsx (hunk 1 above)
Comment (foxymiles) [reply packages/studio-base/src/components/TextMiddleTruncate.tsx:94]: Me too!
