### PR TITLE
Handle empty string in node paths in settings

### LINKED ISSUE #3483: Settings sidebar action callback returns the incorrect path for child nodes with the key `""`
**Description**

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx#L128 is using `""` as a reserved key to refer to the parent, which causes a key collision if there is a child settings node with the key `""`.

### PR DESCRIPTION
**Pull request by foxymiles**
**User-Facing Changes**
None

**Description**
This fixes an issue with paths in nodes in the settings tree that have the empty string `""` as a key.

Fixes #3483

### CODE REVIEW

File: packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx [hunk 1]
```diff
@@ -123,9 +123,10 @@ function NodeEditorComponent(props: NodeEditorProps): JSX.Element {
   const { fields, children } = settings;
   const hasProperties = fields != undefined || children != undefined;
 
-  // Provide stable subpaths so that memoization works.
+  // Provide stable subpaths so that memoization works. We force a dependency on path
+  // here to make sure we reset the cache if the path changes.
   const stablePaths = useMemo<Record<string, readonly string[]>>(
-    () => ({ "": props.path }),
+    () => ({ [Symbol()]: props.path }),
```
Comment (jtbandes) [inline packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx:129]: What is going on here? Could we produce the desired values inside the useMemo instead of mutating below?

Comment (foxymiles) [reply packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx:129]: We need to memoize for each child path so we'd need some kind of `useMemo` in a loop but you can't do that with hooks.

**Review by jhurliman — APPROVED** [review]
